name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    # Triggers on push to main OR on pull requests (if not closed)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      # The OIDC token steps are typically required by the SWA template for secure deployment
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
           
      - name: Build And Deploy (SWA Action)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Your unique deployment token remains here
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_TREE_02CE10D1E }}
          action: "upload"
          
          # --- CRITICAL FIXES FOR SIMPLE HTML APP ---
          # 1. App Location: The root of the repo (where index.html is)
          app_location: "/" 
          
          # 2. API Location: No API for this demo
          api_location: "" 
          
          # 3. Output Location: The output files are also in the root
          output_location: "/" 
          
          # 4. Override Build Command: Prevents the pipeline from running npm install/build on simple HTML
          app_build_command: "echo No build command needed"
          
          # --- END OF CRITICAL FIXES ---
          
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
